name: Publish to PyPI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - id: Python_pip
        name: Python dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          cache: "pip"
      - run: pip install -r requirements.txt

      - name: Build Package
        run: |
          python setup.py sdist

      - name: Upload to PyPi
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USER}}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          sudo apt-get install tree
          tree .
          twine upload dist/*
